version: "3.8"

# Define networks
networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.20.33.0/24
          gateway: 172.20.33.1
  

# Define services
services:
  my_nginx:
    container_name: nginx_uas
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - db
    networks:
      my_network:
        ipv4_address: 172.20.33.2

  db:
    container_name: mysql_uas
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    networks:
      my_network:
        ipv4_address: 172.20.33.3

  php:
    container_name: php_uas
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      my_network:
        ipv4_address: 172.20.33.4
